name          'tdoran-better_file'
version       '0.0.1'
source        'UNKNOWN'
author        'tdoran'
license       'Apache License, Version 2.0'
summary       'UNKNOWN'
description   'UNKNOWN'
project_page  'UNKNOWN'

dependency 'puppetlabs/stdlib'
